{{- $port := .Values.bytebase.option.port -}}
apiVersion: v1
kind: Service
metadata:
  name: bytebase-entrypoint
  namespace: {{ template "bytebase.namespace" . }}
  labels:
    app.kubernetes.io/managed-by: helm
spec:
  # type: LoadBalancer
  type: ClusterIP
  selector:
    app: bytebase
  ports:
  - protocol: TCP
    port: {{ $port }}
    targetPort: {{ $port }}
