# Default values for bytebase.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

bytebase:
  option:
    port: 8080
    # You should set this to the URL where users visits Bytebase.
    external-url: https://bytebase.loofra.cloud
    pg: postgresql://postgres:postgres@postgresql.custom.svc.cluster.local:5432/bytebase
    data: /var/opt/bytebase
  version: 1.7.0
  storage: 2Gi
